### ISSUE TITLE
Readme documentation

### ISSUE THREAD

**Issue by usmanwardag** [usmanwardag/auto_anki#11]

**Comment by usmanwardag** [comment]
Use pycco to generate documentation.
https://pycco-docs.github.io/pycco/

**Comment by usmanwardag** [comment]
Let's add a more descriptive future roadmap with headings.

**Comment by usmanwardag** [comment]
Let's move the previous docs to rubrics to make room for code docs.

**Comment by kriti0207** [comment]
updated the readme
