### ISSUE TITLE
Coverage Target >90%

### ISSUE THREAD

**Issue by usmanwardag** [usmanwardag/auto_anki#20]

**Comment by usmanwardag** [comment]
I have removed a lot of redundant code, and coverage is now up to 76%. Let's target 90%+.

**Comment by usmanwardag** [comment]
Based on coverage analysis, `user_cli.py` does not have any tests. Let's add tests there @sbosenc

**Comment by sbosenc** [comment]
Added coverage for user_cli.py. Overall code coverage is now at 96%.
