### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by usmanwardag** [usmanwardag/auto_anki#6]
Tests, tests, tests ...

**Comment by usmanwardag** [comment]
Let's make sure tests follow similar conventions as the earlier codebase.

**Comment by usmanwardag** [comment]
@sbosenc working on `user_cli` tests. Other than that, our coverage is mostly 100%.

**Comment by sbosenc** [comment]
Added coverage for user_cli.py. Overall code coverage is now at 96%.
